language: java
jdk:
- oraclejdk7
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
before_script: ruby provision/setup-test-environment.rb $PREVIEW_API_KEY $HOD_ENV $HOD_APPLICATION $HOD_DOMAIN
script: mvn verify -Prelease -Dhp.hod.env=$HOD_ENV -Dhp.hod.int.applicationApiKey=$INT_API_KEY -Dhp.hod.int.developerApiKey=$INT_API_KEY -Dhp.hod.int.application=$HOD_APPLICATION -Dhp.hod.int.domain=$HOD_DOMAIN -Dhp.hod.int.developerEmail=$HOD_DEVELOPER_EMAIL
after_success: bash travis.sh
after_script: ruby provision/destroy-test-environment.rb $PREVIEW_API_KEY $HOD_ENV $HOD_APPLICATION $HOD_DOMAIN
env:
  global:
  # SONATYPE_USERNAME
  - secure: tHgE7kxDPCg2qs16hxOQf1V5l0pFIj6dDWCYRh3hod2pIv30y0FqOLorvXxABElpKc2HLGvz9zSgQx1tYeLJNETs3zgX81zgbODApRBMYoQa83OKC02P5kospYdMg52IXPRAYWk/wacEVJJ2daROy6n2NQGFCZQ675SPapt76Ps=
  # SONATYPE_PASSWORD
  - secure: S149VC2Z+JszhAajCixniVCMHNZQMAvqwcW5AG+UZY0ssXoQGSbSuHk2fAgqUA6BBTMEOtZjkgGiR4dpnAk32KEpCXcSfG2DAIa7M7CfXsfbdnYEJNAEn9iSLAaoLHLtdkuQSBl2DHnWw/V6FZgpnnpeat29r4xr6UGp/Oo/Hkg=
  # GPG_PASSPHRASE
  - secure: hXKkf5WpyTkvRUfDpuVcdqknuBpZJjow8YGXpN1bo41hvpv9sekj6M9LClJj4vifYAGwT38bvjK1/qxDebfAhqcGUlr3KLsHaXK3QkzUwBnvjyOK+im9Z7Ipcc1/H6c0+ZLv3TwhovTj7RuIZFyGTkun6rINdW8kYaS8YpNFpp8=
  # GPG_KEYID
  - secure: OzPm3bYdM8Dg9AYigGqM8cEv4bKbeHY+MoljGnsX7edMt1uwtglW/VzGVWIEQF57hTaPA+/3orGOJak6cn2s9355mZlo5lCbJz43e6LyKX5ryX5jPe4jgpgwFSwH7hin7hkP4VkjT+Wb/4UTaiXRmj3LkzK1HA7EssNcw2j/9us=
  # GPG_KEY
  - secure: YvX/muwjVf+xQughSFMctniIg4sxpTmq6wfet6Un8x6cinKTWXQZNm0DdadRwZtkVq60Ddne2Yweb4E0xnOn86h6ACEAQcLrnTuv6UWx8u/M09Rp7FHCdMnFhoaJpeU6QDNJJkV152bU9u2gbYikLGcyanK8sU/wuGo6mkBvuAc=
  # API_KEY
  - secure: FNjOFgBF2VV3xFS769ikIWGSRvkEOohW6bm0G+qtXY6C0ApZHtfIoP4EJ39D1zWbmS7GNDOdIMGDkT2tkNwstRUgaBV49z8l5KO6LKtvMDzfq5Pd8LnZpyigRbdIyA4fSvhwkMEtIJ02yL3EzNwk2ZBNQC+jnW7HEkOmEuPwvag=
  # INT_API_KEY
  - secure: PWzpD0Ac9ELCdkwIMyHf8ylq3Cp3rrFZZ4+ga3fV+/XAn2k8AJ1/X3KZuRxiLj8e7McEyGXh8AJT35xSoEwLfvLi+iQp0SqKGPIhY771SpZBQcXph8n28NoiGvFwXp0l/FQwiYg9qGfhF5pT2NwFnmavrp+h9SQ7ruZffrNo8Wc=
  # PREVIEW_API_KEY
  - secure: CJ++BiYgUbXbV+T9IYkuecKO2Wlhn1ow+kJSipoJ2gypH+unEU4DmQVewesGTINXgeD8fkJq/Kbq2jd+EI8Z/+HIM3CaH4lVUaWl4PzHtKvvrrlOaoefkUhW31Z29Fv4ILVoXk8URlZJXwroPHUrrtXc+TBxevifNa7z4VgX4oI=
  # GITHUB_TOKEN
  - secure: lFlg8557sEpm61f8G/3d0bz/C/arHJxEX7ag5q8bYNtwxXFf1Roikwr7M8PfD7CKYqdwIMxrtsoMsaj2D4PeFKTJWNWA/K46yg2rU4q7qZounPJnAwXQeKyaO7KsuO3d1Cez5cQhuypfOL02+d5t2vWU3L4R1sbQGg1HokCwbwU=
  # HOD_APPLICATION
  - secure: T9pqvu/HdX9oVpwSSjeWY/DW6eoquE0Dr9om+23UVnQ27S5/NtcKKdTZfZwrDFNuNKHuwIeqWerF5yl13tkMrU++fHNhwbr7RXZAW7PZiKHX+lQ+Ny7g8yxZth6YEVJ2YtRgrbb+FSVHc2KwiEqo9O03DBmvVPEZBOyMaVNWIcA=
  # HOD_DOMAIN
  - secure: PPG2bfc7BdCsMC6AU6viHTVXYZyjW8MD4iCOhjRvs/4B/BBLaIwElMNFbgLVPkmrK3ol1lM0CH4ydKg5i7stZhdjIiytX/QL9qV/LLv1XJ1ouvLpvkHyUXsYCa5MHTzK3Cqwh4szzEz3/PmAeyY92UJEym+W8vs8DbBmZl+oGn8=
  # HOD_DEVELOPER_EMAIL
  - secure: aWJtwYXJRdiIdgh4VvkTYQfdUcI2giq2AQSJVJEP5ad9Np4UwXTBV+1lZDwK/10vJEJ/XDXQWiHRZpyr06v/05edFV7xAto7Ur4RUL8gfR9UKBx9yiafkr/EcDNXa2zq/pDbEgmuPCYtiT3O9+3L3fuZXyhBAT2U4I9aKxrZgYM=
  - HOD_ENV=INTEGRATION
