language: java
jdk:
- oraclejdk7
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
#before_script: ruby provision/setup-test-environment.rb $DEV_API_KEY_PLACEHOLDER
script: mvn verify -Prelease -Dhp.hod.apiKey=$API_KEY -Dhp.dev.hod.apiKey=$DEV_API_KEY -Dhp.dev.placeholder.hod.apiKey=$DEV_API_KEY_PLACEHOLDER -Dhp.hod.env=DEVELOPMENT -Dmaven.test.skip=true
after_success: bash travis.sh
#after_script: ruby provision/destroy-test-environment.rb $DEV_API_KEY_PLACEHOLDER
env:
  global:
  # SONATYPE_USERNAME
  - secure: tHgE7kxDPCg2qs16hxOQf1V5l0pFIj6dDWCYRh3hod2pIv30y0FqOLorvXxABElpKc2HLGvz9zSgQx1tYeLJNETs3zgX81zgbODApRBMYoQa83OKC02P5kospYdMg52IXPRAYWk/wacEVJJ2daROy6n2NQGFCZQ675SPapt76Ps=
  # SONATYPE_PASSWORD
  - secure: S149VC2Z+JszhAajCixniVCMHNZQMAvqwcW5AG+UZY0ssXoQGSbSuHk2fAgqUA6BBTMEOtZjkgGiR4dpnAk32KEpCXcSfG2DAIa7M7CfXsfbdnYEJNAEn9iSLAaoLHLtdkuQSBl2DHnWw/V6FZgpnnpeat29r4xr6UGp/Oo/Hkg=
  # GPG_PASSPHRASE
  - secure: hXKkf5WpyTkvRUfDpuVcdqknuBpZJjow8YGXpN1bo41hvpv9sekj6M9LClJj4vifYAGwT38bvjK1/qxDebfAhqcGUlr3KLsHaXK3QkzUwBnvjyOK+im9Z7Ipcc1/H6c0+ZLv3TwhovTj7RuIZFyGTkun6rINdW8kYaS8YpNFpp8=
  # GPG_KEYID
  - secure: OzPm3bYdM8Dg9AYigGqM8cEv4bKbeHY+MoljGnsX7edMt1uwtglW/VzGVWIEQF57hTaPA+/3orGOJak6cn2s9355mZlo5lCbJz43e6LyKX5ryX5jPe4jgpgwFSwH7hin7hkP4VkjT+Wb/4UTaiXRmj3LkzK1HA7EssNcw2j/9us=
  # GPG_KEY
  - secure: YvX/muwjVf+xQughSFMctniIg4sxpTmq6wfet6Un8x6cinKTWXQZNm0DdadRwZtkVq60Ddne2Yweb4E0xnOn86h6ACEAQcLrnTuv6UWx8u/M09Rp7FHCdMnFhoaJpeU6QDNJJkV152bU9u2gbYikLGcyanK8sU/wuGo6mkBvuAc=
  # API_KEY
  - secure: FNjOFgBF2VV3xFS769ikIWGSRvkEOohW6bm0G+qtXY6C0ApZHtfIoP4EJ39D1zWbmS7GNDOdIMGDkT2tkNwstRUgaBV49z8l5KO6LKtvMDzfq5Pd8LnZpyigRbdIyA4fSvhwkMEtIJ02yL3EzNwk2ZBNQC+jnW7HEkOmEuPwvag=
  # DEV_API_KEY
  - secure: HDgO4NFKo5zYhafi82WauFIZx1VJmoyzMNkoFuQ6IobXOWVwN66NP4TEuidGyepUDPObj6RO4bLUc2FYaNk18AUfFtUpMJ5anFPdZa8/yYiZxQ1lhVa3UbEw889SY2dByrMZSb9rMTrbYuo1yc1OpGS9Iwovj2MUkl+wiHjABDw=
  # GITHUB_TOKEN
  - secure: lFlg8557sEpm61f8G/3d0bz/C/arHJxEX7ag5q8bYNtwxXFf1Roikwr7M8PfD7CKYqdwIMxrtsoMsaj2D4PeFKTJWNWA/K46yg2rU4q7qZounPJnAwXQeKyaO7KsuO3d1Cez5cQhuypfOL02+d5t2vWU3L4R1sbQGg1HokCwbwU=
  # DEV_API_KEY_PLACEHOLDER
  - secure: HD1gkFJe4/zCPjp5lwT3PQXCpC+LQrwvHOhFGAxerOZNOQWPAYUcwEMnJU97YlMyi/8D8cXaAXoY/+9ppwbBPHDaFWWOqExDRst2XLN7ab+UXwjbags3Bp6dkvstauPGIcYR/RLi9XOwY+g4yGtAMK/qwWFf2g2YWyV/oDRUg1Y=
